// scripts/make-ways-in.mjs
//
// Purpose: write apps/overview.mdx, "Every way to reach Trillion", from the Trillion app's own records, so the docs
// list exactly the apps and AI connections the app itself offers:
//   - src/devices.json     : the Trillion apps for a person's devices, each with its install link per system or its
//                            honest not-yet words (the same rows start_setup and the app's devices section read)
//   - src/ai-clients.json  : every AI app Trillion connects to (the same rows the app's connect screen reads)
// scripts/ways-in.json says which docs page tells more about a row (by row id) and the page's own words.
//
// Invariants:
//   1. Nothing here names a device, system or AI app. A new row in either Trillion file appears on the next run.
//   2. A row with no install link shows its not-yet words, never a guessed link.
//   3. A row with no docs page links to the app's own connect screen named in ways-in.json, never to a missing page.
//   4. `--check` writes nothing and fails when apps/overview.mdx differs from what the records say.
//
// Usage: node scripts/make-ways-in.mjs [--check]   (TRILLION_REPO points at the Trillion checkout, as for generate-docs)

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { site } = JSON.parse(readFileSync(join(root, 'docs.manifest.json'), 'utf8'));
const config = JSON.parse(readFileSync(join(root, 'scripts', 'ways-in.json'), 'utf8'));
const trillionRepo = process.env[site.look.repository.environmentOverride]
  ?? join(root, '..', site.look.repository.directoryBesideThisOne);
const read = (file) => {
  const path = join(trillionRepo, file);
  if (!existsSync(path)) throw new Error(`cannot read ${path} (set ${site.look.repository.environmentOverride})`);
  return JSON.parse(readFileSync(path, 'utf8'));
};
const { systems, devices } = read(config.sources.devices);
const { clients } = read(config.sources.ai_clients);

const escapeText = (text) => String(text).replace(/[{}<>]/g, (ch) => `&#${ch.charCodeAt(0)};`);
const attr = (text) => String(text).replace(/"/g, '&quot;');
const systemLabel = new Map(systems.map((system) => [system.id, system.label]));
const listOf = (names) => (names.length > 1 ? `${names.slice(0, -1).join(', ')} ${config.words.or} ${names.at(-1)}` : names[0]);
const systemsOf = (entry) => (entry.systems === 'any' ? '' : ` ${config.words.for} ${listOf(entry.systems.map((id) => systemLabel.get(id) ?? id))}`);
const pageFor = (id) => config.pages[id] ?? null;

const deviceCard = (device) => {
  const page = pageFor(device.id);
  const lines = device.get.map((entry) => (entry.href
    ? `- [${escapeText(entry.label)}](${entry.href})${escapeText(systemsOf(entry))}`
    : `- ${escapeText(entry.label)}: ${escapeText(entry.not_yet)}`));
  // Install links sit inside the card, so the card itself is not a link; its docs page is the last line.
  return [
    `<Card title="${attr(device.title)}">`,
    `  ${escapeText(device.body)}`,
    '',
    ...lines.map((line) => `  ${line}`),
    ...(page ? [`  - [${escapeText(config.words.more)}](${page})`] : []),
    '</Card>',
  ].join('\n');
};

const clientCard = (client) => {
  const page = pageFor(client.id);
  return [
    `<Card title="${attr(client.label)}" href="${page ?? config.connect_screen}">`,
    `  ${escapeText(client.lead)}`,
    '</Card>',
  ].join('\n');
};

const body = [
  '---',
  `title: "${attr(config.words.title)}"`,
  `description: "${attr(config.words.description)}"`,
  '---',
  '',
  `{/* Generated by scripts/make-ways-in.mjs from the Trillion app's ${config.sources.devices} and ${config.sources.ai_clients}. Never edit by hand. */}`,
  '',
  escapeText(config.words.intro),
  '',
  `## ${escapeText(config.words.devices_heading)}`,
  '',
  '<CardGroup cols={2}>',
  ...devices.map(deviceCard),
  '</CardGroup>',
  '',
  `## ${escapeText(config.words.ai_heading)}`,
  '',
  escapeText(config.words.ai_intro),
  '',
  '<CardGroup cols={2}>',
  ...clients.map(clientCard),
  '</CardGroup>',
  '',
].join('\n');

const target = join(root, config.output);
if (process.argv.includes('--check')) {
  if (!existsSync(target) || readFileSync(target, 'utf8') !== body) {
    console.error(`Out of date, run npm run docs:ways-in: ${config.output}`);
    process.exit(1);
  }
  console.log(`${config.output} matches the Trillion app's records`);
} else {
  writeFileSync(target, body);
  console.log(`wrote ${config.output}: ${devices.length} apps, ${clients.length} AI apps`);
}
